[package]
name = "meme-sniper"
version = "0.1.0"
edition = "2021"

[dependencies]
starknet = "0.12.0"
url = "2.5.4"
reqwest = "0.12.9"
tokio = { version = "1.0", features = ["rt-multi-thread", "macros"] }